Farfetch/rules-framework

appveyor.yml, run-tests.ps1
Adapts build scripting to recover SonarQube code coverage metrics. Now using SonarQube default format for code coverage upload.
=> [FIX] Fix code coverage by switching format to SonarQube generic format

.github/workflows/dotnet-build.yml
Fixes the GitHub actions build target:
- Was seeking versions starting on v*
- Now it is able to seek versions on the format example 1.0.1-beta
=> Change 'include' glob pattern for query version tag

.github/CODE_OF_CONDUCT.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SECURITY.md, CONTRIBUTING.md, README.md
This merge request is adding missing files/information as required by Farfetch to gain ownership of a open source project.
Closes #30.
Closes #31.
Closes #32.
Closes #33.
=> Create missing documentation (Farfetch ownership requirements)

docs/add-rules.md, src/Rules.Framework/Builder/Validation/ValueConditionNodeValidator.cs, src/Rules.Framework/Core/Operators.cs, src/Rules.Framework/Evaluation/ValueEvaluation/Dispatchers/ConditionEvalDispatchProvider.cs, src/Rules.Framework/Evaluation/ValueEvaluation/EndsWithOperatorEvalStrategy.cs, src/Rules.Framework/Evaluation/ValueEvaluation/OperatorEvalStrategyFactory.cs, src/Rules.Framework/Evaluation/ValueEvaluation/StartsWithOperatorEvalStrategy.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/EndsWithOperatorEvalStrategyTests.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/StartsWithOperatorEvalStrategyTests.cs
Adds support for doing `StartsWith` and `EndsWith` comparisons
Closes #55.
=> Add StartsWith and EndsWith Operator

docs/add-rules.md, src/Rules.Framework/Builder/Validation/ValueConditionNodeValidator.cs, src/Rules.Framework/Core/Operators.cs, src/Rules.Framework/Evaluation/ValueEvaluation/CaseInsensitiveEndsWithOperatorEvalStrategy.cs, src/Rules.Framework/Evaluation/ValueEvaluation/CaseInsensitiveStartsWithOperatorEvalStrategy.cs, src/Rules.Framework/Evaluation/ValueEvaluation/Dispatchers/ConditionEvalDispatchProvider.cs, src/Rules.Framework/Evaluation/ValueEvaluation/OperatorEvalStrategyFactory.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/CaseInsensitiveEndsWithOperatorEvalStrategyTests.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/CaseInsensitiveStartsWithOperatorEvalStrategyTests.cs
Adds operator evaluators CaseInsensitiveStartsWith and CaseInsensitiveEndsWith.
Closes #57. 
=> Adds operator evaluators CaseInsensitiveStartsWith and CaseInsensitiveEndsWith

src/Rules.Framework/RulesEngine.cs, tests/Rules.Framework.Tests/RulesEngineTests.cs
Inserting rules AtBottom causes exception when rules data source is empty for a ContentType 
Closes #50.
- [X ] Code follows the [code rules guidelines](../CONTRIBUTING.md#code-rules) of this project
- [X ] Commit messages follow the [commit rules](../CONTRIBUTING.md#commit-rules) of this project
- [ X] I have self-reviewed my changes before submitting this pull request
- [X ] I have covered new/changed code with new tests and/or adjusted existent ones
- [X ] I have made changes necessary to update the documentation accordingly
=> [BUG #50]Implemented Solution and Unit Test

README.md, docs/get-unique-condition-types.md, src/Rules.Framework.Providers.InMemory/Rules.Framework.Providers.InMemory.csproj, src/Rules.Framework.Providers.MongoDb/Rules.Framework.Providers.MongoDb.csproj, src/Rules.Framework/Builder/ConfiguredRulesEngineBuilder.cs, src/Rules.Framework/ConditionTypeExtractor.cs, src/Rules.Framework/IConditionTypeExtractor.cs, src/Rules.Framework/Rules.Framework.csproj, src/Rules.Framework/RulesEngine.cs, tests/Rules.Framework.IntegrationTests/Rules.Framework.IntegrationTests.csproj, tests/Rules.Framework.Providers.InMemory.Tests/Rules.Framework.Providers.InMemory.Tests.csproj, tests/Rules.Framework.Providers.MongoDb.IntegrationTests/Rules.Framework.Providers.MongoDb.IntegrationTests.csproj, tests/Rules.Framework.Providers.MongoDb.Tests/Rules.Framework.Providers.MongoDb.Tests.csproj, tests/Rules.Framework.Tests/ConditionTypeExtractorTests.cs, tests/Rules.Framework.Tests/Rules.Framework.Tests.csproj, tests/Rules.Framework.Tests/RulesEngineTests.cs
The purpose is to be able to fetch the unique condition types associated with the rules persisted on the data source for a specific content type.
i.e. content-type "ABC" has condition types 1 and 2 for rules between dates A and B, and this functionality would let us know that we would need to fill conditions 1 and 2 for rules evaluation on date interval between A and B.
Closes #22 .
=> Implemented GetConditionType method and unit test

src/Rules.Framework/RulesEngine.cs
Re-adds the AddDays(1) instruction to the RulesEngine, done in [this fix](https://github.com/Farfetch/rules-framework/pull/71) (it didn't solve the issue)
=> fix: Re-add addDays in rules engine

src/Rules.Framework/Builder/Validation/ValueConditionNodeValidator.cs, src/Rules.Framework/Core/Operators.cs, src/Rules.Framework/Evaluation/ValueEvaluation/Dispatchers/ConditionEvalDispatchProvider.cs, src/Rules.Framework/Evaluation/ValueEvaluation/NotContainsOperatorEvalStrategy.cs, src/Rules.Framework/Evaluation/ValueEvaluation/OperatorEvalStrategyFactory.cs, tests/Rules.Framework.IntegrationTests.Common/Scenarios/Scenario4/DiscountConditions.cs, tests/Rules.Framework.IntegrationTests/Tests/Scenario4/DiscountCampaignTests.cs, tests/Rules.Framework.Tests/Builder/RuleBuilderTests.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/OperatorEvalStrategyFactoryTests.cs
Adding 'not contains' operator, reported in #89 
=> feat: adding not contains operator

.github/workflows/dotnet-build.yml, docs/add-rules.md, src/Rules.Framework/Builder/Validation/ValueConditionNodeValidator.cs, src/Rules.Framework/Core/Operators.cs, src/Rules.Framework/Evaluation/ValueEvaluation/Dispatchers/ConditionEvalDispatchProvider.cs, src/Rules.Framework/Evaluation/ValueEvaluation/NotEndsWithOperatorEvalStrategy.cs, src/Rules.Framework/Evaluation/ValueEvaluation/NotStartsWithOperatorEvalStrategy.cs, src/Rules.Framework/Evaluation/ValueEvaluation/OperatorEvalStrategyFactory.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/NotEndsWithOperatorEvalStrategyTests.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/NotStartsWithOperatorEvalStrategyTests.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/OperatorEvalStrategyFactoryTests.cs
Implements support for the "NotStartsWith" and "NotEndsWith" operators.
- Issue #91 
=> feat: add support for notStartsWith and notEndsWith operators

src/Rules.Framework/Builder/ConfiguredRulesEngineBuilder.cs, src/Rules.Framework/Builder/RulesEngineOptionsValidator.cs, src/Rules.Framework/Builder/Validation/ValueConditionNodeValidator.cs, src/Rules.Framework/Builder/ValueConditionNodeBuilder.cs, src/Rules.Framework/Core/DataTypes.cs, src/Rules.Framework/Evaluation/ValueEvaluation/Dispatchers/DataTypesConfigurationProvider.cs, src/Rules.Framework/RulesEngineOptions.cs, tests/Rules.Framework.Tests/Builder/RuleEngineOptionsValidatorTests.cs
This is part 1 of fixing the problem with the "in" operator while using the rule on memory #54 
=> fix: operator in for rule on memory part 1

CONTRIBUTING.md
Add rule to contributing documentation for using var implicit declaration.
=> [CHORE] Add rule to CONTRIBUTING.md to use var declaration

src/Rules.Framework/Builder/Validation/ValueConditionNodeValidator.cs, src/Rules.Framework/Core/Operators.cs, src/Rules.Framework/Evaluation/OperatorsMetadata.cs, src/Rules.Framework/Evaluation/ValueEvaluation/NotInOperatorEvalStrategy.cs, src/Rules.Framework/Evaluation/ValueEvaluation/OperatorEvalStrategyFactory.cs, tests/Rules.Framework.Tests/Evaluation/ValueEvaluation/NotInOperatorEvalStrategyTests.cs
Added Operators.NotIn for arrays (#113)
=> feat: added Operators.NotIn for arrays Part 1

src/Rules.Framework.Providers.InMemory/Rules.Framework.Providers.InMemory.csproj, src/Rules.Framework.Providers.MongoDb/Rules.Framework.Providers.MongoDb.csproj, src/Rules.Framework.WebUI/Rules.Framework.WebUI.csproj, tests/Rules.Framework.Providers.InMemory.IntegrationTests/Tests/Scenario5/BestServerTests.cs, tests/Rules.Framework.Providers.MongoDb.IntegrationTests/Tests/Scenaro5/BestServerTests.cs, tests/Rules.Framework.WebUI.Tests/Rules.Framework.WebUI.Tests.csproj
Update rules.framework NuGet package version in order to use the operator.NotIn and updated integration tests (#112)
=> feat: added Operators.NotIn for arrays Part 2

samples/Rules.Framework.WebUI.Sample/Engine/RulesEngineProvider.cs, samples/Rules.Framework.WebUI.Sample/Rules/RulesRandomFactory.cs, src/Rules.Framework.WebUI/Dto/ContentTypeDto.cs, src/Rules.Framework.WebUI/Handlers/GetContentTypeHandler.cs, src/Rules.Framework.WebUI/index.html
All of these changes are on Rules.Framework Web UI
- fixed #120 
- a better way to show conditions in string format (pretty)
- changed rules "value" labels to "content"
- condition operand is a string empty 
=> fix: fixed the web ui filter rules by value (content)

.github/workflows/dotnet-build.yml, .github/workflows/dotnet-publish.yml, samples/Rules.Framework.InMemory.Sample/Rules.Framework.InMemory.Sample.csproj, src/Rules.Framework.Providers.MongoDb/Rules.Framework.Providers.MongoDb.csproj, src/Rules.Framework.WebUI/Rules.Framework.WebUI.csproj, src/Rules.Framework.WebUI/WebUIMiddleware.cs, src/Rules.Framework/Rules.Framework.csproj, tests/Rules.Framework.IntegrationTests/Rules.Framework.IntegrationTests.csproj, tests/Rules.Framework.IntegrationTests/RulesFromJsonFile.cs, tests/Rules.Framework.Providers.InMemory.IntegrationTests/Rules.Framework.Providers.InMemory.IntegrationTests.csproj, tests/Rules.Framework.Providers.InMemory.Tests/Rules.Framework.Providers.InMemory.Tests.csproj, tests/Rules.Framework.Providers.MongoDb.IntegrationTests/Rules.Framework.Providers.MongoDb.IntegrationTests.csproj, tests/Rules.Framework.Providers.MongoDb.Tests/Rules.Framework.Providers.MongoDb.Tests.csproj, tests/Rules.Framework.Tests/Rules.Framework.Tests.csproj, tests/Rules.Framework.WebUI.Tests/Rules.Framework.WebUI.Tests.csproj
Upgrades the packages under .Net Standard 2.0 to .Net Standard 2.1.
Also upgrades some of the packages to newer versions and fixes an issue on failing tests (dependent on the machine culture).
=> Upgrade to .Net Standard 2.1

samples/Rules.Framework.InMemory.Sample/Engine/RulesService.cs, src/Rules.Framework/Builder/FluentComposedConditionNodeBuilder.cs, src/Rules.Framework/Builder/IFluentComposedConditionNodeBuilder.cs, src/Rules.Framework/Builder/IRootConditionNodeBuilder.cs, src/Rules.Framework/Builder/RootConditionNodeBuilder.cs, src/Rules.Framework/Condition.cs, src/Rules.Framework/Extensions/GenericSearchArgsExtensions.cs, tests/Rules.Framework.IntegrationTests.Common/Scenarios/Scenario6/Scenario6Data.cs, tests/Rules.Framework.IntegrationTests.Common/Scenarios/Scenario7/Scenario7Data.cs, tests/Rules.Framework.IntegrationTests.Common/Scenarios/Scenario8/Scenario8Data.RoyalFlush.cs, tests/Rules.Framework.IntegrationTests.Common/Scenarios/Scenario8/Scenario8Data.Straight.cs, tests/Rules.Framework.IntegrationTests.Common/Scenarios/Scenario8/Scenario8Data.cs, tests/Rules.Framework.IntegrationTests/Scenarios/Scenario2/CarInsuranceAdvisorTests.cs, tests/Rules.Framework.IntegrationTests/Scenarios/Scenario3/BuildingSecuritySystemControlTests.cs, tests/Rules.Framework.IntegrationTests/Scenarios/Scenario4/DiscountCampaignTests.cs, tests/Rules.Framework.IntegrationTests/Scenarios/Scenario8/TexasHoldEmPokerSingleCombinationsTests.cs, tests/Rules.Framework.Providers.InMemory.IntegrationTests/Scenarios/Scenario2/CarInsuranceAdvisorTests.cs, tests/Rules.Framework.Providers.InMemory.IntegrationTests/Scenarios/Scenario3/BuildingSecuritySystemControlTests.cs, tests/Rules.Framework.Providers.MongoDb.IntegrationTests/Scenarios/Scenario2/CarInsuranceAdvisorTests.cs, tests/Rules.Framework.Providers.MongoDb.IntegrationTests/Scenarios/Scenario3/BuildingSecuritySystemControlTests.cs, tests/Rules.Framework.Providers.MongoDb.IntegrationTests/Scenarios/Scenaro5/BestServerTests.cs, tests/Rules.Framework.Providers.MongoDb.Tests/RuleFactoryTests.cs, tests/Rules.Framework.Tests/ConditionTests.cs, tests/Rules.Framework.Tests/Extensions/GenericRuleExtensionsTests.cs, tests/Rules.Framework.Tests/Extensions/GenericSearchArgsExtensionsTests.cs, tests/Rules.Framework.Tests/Providers/InMemory/RuleFactoryTests.cs, tests/Rules.Framework.Tests/RulesEngineTests.cs, tests/Rules.Framework.Tests/Validation/SearchArgsValidatorTests.cs
* Modify calls to use the new Condition ctor
* Turn Condition parameterless obsolete
* Renamed method in condition builders that accept a condition to Condition()
=> Set the Condition parameterless constructor obsolete

samples/Rules.Framework.WebUI.Sample/Enums/ContentTypes.cs, src/Rules.Framework.WebUI/Dto/FilterDto.cs, src/Rules.Framework.WebUI/Dto/RuleDto.cs, src/Rules.Framework.WebUI/Dto/RuleStatusDto.cs, src/Rules.Framework.WebUI/Dto/RuleStatusDtoAnalyzer.cs, src/Rules.Framework.WebUI/Extensions/RuleDtoExtensions.cs, src/Rules.Framework.WebUI/Handlers/GetContentTypeHandler.cs, src/Rules.Framework.WebUI/Handlers/GetIndexPageHandler.cs, src/Rules.Framework.WebUI/Handlers/GetRulesHandler.cs, src/Rules.Framework.WebUI/WebUIRequestHandlerBase.cs, src/Rules.Framework.WebUI/index.html, tests/Rules.Framework.WebUI.Tests/Extensions/RuleDtoExtensionsTests.cs, tests/Rules.Framework.WebUI.Tests/Handlers/GetRulesHandlerTests.cs
- Added Web UI able to set cutover dates for the rules 
- Content type is no longer required, you may search into all rules 
- Changed rules status from inactive to expired
- Moved to the backend the responsibility to filter the rules
Related to issue #105 
=> Web UI added cut over dates

src/Rules.Framework/Evaluation/Compiled/RuleConditionsExpressionBuilder.cs, src/Rules.Framework/Evaluation/OperatorMetadata.cs, src/Rules.Framework/Rules.Framework.csproj
Add multi-targeting to allow support of Rules.Framework under .NET Framework 4.8 (through .NET Standard 2.0).
=> Backwards support for .NET Standard 2.0 (support .NET Framework 4.8)

src/Rules.Framework.WebUI/Handlers/GetRulesHandler.cs, src/Rules.Framework.WebUI/Rules.Framework.WebUI.csproj, src/Rules.Framework.WebUI/WebUIMiddleware.cs
Updated Web UI to support .NET Standard 2.0
Closes #160.
=> feat: Updated Web UI to support .NET Standard 2.0
